### ISSUE TITLE
Module should reflect CWD in name

### ISSUE THREAD

**Issue by ssh6** [CU-CommunityApps/CD_cwd_events_localist_pull#18]
https://github.com/CU-CommunityApps/CD_cwd_events_localist_pull/blob/46f125ea3171c02cc9a24c5cf84d8baab53164a1/cwd_events_localist_pull.info.yml#L1

(To include ":" or not would be a separate decision)

I suggest "CWD Localist Events Pull"

**Comment by alisonjo315** [comment]
(!! last I checked, which was a bit ago !!) Drupal modules get finicky about colons in module names. Other than that, yeppers absolutely it should have CWD (or better yet, CD) in the "human name."

**Comment by ssh6** [comment]
Doesn't matter to me, but I'm guessing there should be some sort of consistency.  

(CD developed modules/themes)
PROJECT
--
Cornell Dining Intergration
Localist Events Pull
CWD: Find Conent with links
CWD: Highlight Menu Link
CWD Twig Utility
CWD Cornell Base
CWD Admin
Student & Campus Life
Cornell University CWD SSIT Theme
CWD SSIT SCL install profile

**Comment by alisonjo315** [comment]
Ugh, yeah, it's annoying we still use CWD when CWD hasn't existed for like 5+ years (I came on almost 5 years ago and it barely or didn't exist then).

CD Demo is another example repo! 

Ok well, you're right.

My other rec, since we're renaming, is to call it an importer, so:
CWD Localist Importer

And I'd trim "custom module" from the start of the description text, just to be slightly more succinct.

...I'd really like to call it "CWD Cornell Calendar Importer" and only mention Localist in the description, bc Localist is a more behind-the-scenes type thing, BUT I'm getting the feeling that ppl see Cornell Calendar as separate from Weill Calendar, rather than a generic term that refers to both calendars.....?

**Comment by ssh6** [comment]
We just don't want to confuse the name of this module with https://github.com/CU-CommunityApps/CD_cwd_events, which has different functionality.  (I confused it one day... thought it was a newer version of this one)

**Comment by alisonjo315** [comment]
Good point - and, that one needs a rename, too, it's way too vague.

When we talk about these two modules, when deciding which to use on projects, we always say that this one imports events, whereas the other one "embeds" events (sometimes we say it's an "embed widget").

(In conclusion 😁 I think "importer" is a good descriptor.)

**Comment by alisonjo315** [comment]
"Circling back," as they say...

I'm planning to go with:
CWD Localist Importer

Let me know if you have any objections/concerns/better ideas.  I'll be sharing with + soliciting feedback from my CWD/CD colleagues, too.

Thanks!

**Comment by stacypendell** [comment]
No opinion here about the "Importer" vs "Pull" part, but I think (1) we've used CWD often enough that we should probably keep using it for consistency, even where Cornell/CU or CD might make more sense - or, make a plan to start switching all of them to eventually match, and (2) "Localist" matters to me because I can envision a future in which Cornell switches to some other calendar tool and we have to write a new module and easily tell the two apart, or some sites want to use Google calendar instead, or who knows what ... this module is specific to Localist, even though that sounds a bit back-end-ish.

Agree that renaming the other, even more vaguely named CD_cwd_events would be helpful too.

**Comment by alisonjo315** [comment]
Thank you for the input, Stacy!

I'll submit a PR.
